Interop monorepo
OffchainLabs/arbitrum-interop-quickstart pull request #2
Opened 2021-05-03 15:44 UTC by mahsamoosavi

2021-05-04 12:59 UTC, fredlacs requested changes
Left a couple comments on specific parts of the code.
I think we should probably also add a linter for solidity/javascript to this project as in the Arbitrum monorepo - which uses it as a [pre-commit hook](https://github.com/OffchainLabs/arbitrum/blob/77f142c5ea404552243772a8a1ce5d5a38034c3a/.pre-commit-config.yaml#L46-L60).

2021-05-04 12:59 UTC, fredlacs commented on packages/greeter/package.json
> +    "dotenv": "^8.2.0"
Are we using dotenv to configure anything in the repo?

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_withdraw/scripts/deploy.js
> +    const infuraKey = process.env.INFURA_KEY
Should we switch to using a `.env` file to configure infura key and private key?
I think it may be cleaner and easier for users than setting env variables.

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_withdraw/scripts/deploy.js
> +    const l2Provider = new ethers.providers.JsonRpcProvider(`https://kovan4.arbitrum.io/rpc`)
I think we should load the rpc endpoint from a env variable or config file to make it easier to change in the future

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_withdraw/README.md
> +Once the script is successfully executed, you can go to the [Arbitrum block explorer](https://explorer.offchainlabs.com/#/), enter your public key, and see the amount of ETH that has been depsoyyed t
Not a big difference but I think we should link to the explorer using this link `https://explorer.arbitrum.io` or 

I believe you meant to say `address` (which is the first 20 bytes of the hash of the user's public key).

Also `depsoyyed` should be `withdrawn`.

If a user looks at his account in the explorer after a withdraw, they will see the L2 balance deducted but the L1 balance still won't be incremented - as they need to wait for the rollup's confirmation period. Their withdrawal needs to be triggered in the L1 after the rollup confirmation period - I believe we also want to explain these concepts in this tutorial.

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_withdraw/README.md
> +<img align=“center” src="https://offchainlabs.com/c79291eee1a8e736eebd9a2c708dbe44.png" width="350" height="100">
Hm not sure why but doesn't seem like the img actually aligned to the centre.

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_withdraw/hardhat.config.js
> +      url: "https://kovan.infura.io/v3/" + process.env["INFURA_KEY"],
This is only needed if we're explaining the L1 part of the withdraw process

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_withdraw/contracts/Withdraw.sol
> +    function withdrawEth(address _destAddress) public payable
There are a couple different ways to trigger this:
 - User tx to a contract that calls `arbsys.withdrawEth` or `arbsys. sendTxToL1`
 - User tx that calls straight up `arbsys.withdrawEth` or `arbsys. sendTxToL1`
 
 We should cover both in the tutorial

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_withdraw/contracts/Arbsys.sol
> +interface ArbSys {
I think we want the Arbsys contract interface be a part of `packages/arb-shared-dependencies`

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_deposit/package.json
> +    "build": "hardhat compile"
Users might find it easier if we add a command to trigger the deploy:
```json
    "deploy": "hardhat run scripts/deploy.js"
```

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_deposit/package.json
> +    "build": "hardhat compile"
Also, the deploy contract not only deploys the contract, but also triggers the deposit.
To make this more explicit we should either rename the script or separate the actions into different scripts

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_deposit/scripts/deploy.js
> +    const l1Provider = new ethers.providers.JsonRpcProvider(`https://kovan.infura.io/v3/${infuraKey}`)
as in the withdraw, we probably want to parse this from a config file or env variable instead of hardcoding kovan.infura and kovan4.arbitrum

2021-05-04 12:59 UTC, fredlacs commented on packages/eth_deposit/contracts/Payment.sol
> +    function depositEther(address _destAddress) public payable
As in the eth_withdraw package, we probably want to show there are different ways to deposit eth, and that you don't necessarily need to deploy a contract to do it.

In the inbox itself there are a couple different ways to get a deposit into the L2 - we can explore them and the different nuances here or in a different tutorial/documentation.

2021-05-04 14:47 UTC, mahsamoosavi commented on packages/greeter/package.json
> +    "dotenv": "^8.2.0"
previously we did not. But I guess we do now, as we have things like the Infura key in the env file

2021-05-04 14:51 UTC, mahsamoosavi commented on packages/eth_withdraw/scripts/deploy.js
> +    const infuraKey = process.env.INFURA_KEY
Agreed and done. Do you think it's good to  add the ```.env``` to the ```.gitignore``` and create a ```.sample-env``` that shows how to add these variables?

2021-05-04 14:51 UTC, mahsamoosavi commented on packages/eth_withdraw/scripts/deploy.js
> +    const l2Provider = new ethers.providers.JsonRpcProvider(`https://kovan4.arbitrum.io/rpc`)
Agreed and Done.

2021-05-04 14:52 UTC, mahsamoosavi commented on packages/eth_withdraw/README.md
> +Once the script is successfully executed, you can go to the [Arbitrum block explorer](https://explorer.offchainlabs.com/#/), enter your public key, and see the amount of ETH that has been depsoyyed t
Changed the link and corrected the ```depsoyyed```.

Will spend some time to explain these more and better.

2021-05-04 14:57 UTC, mahsamoosavi commented on packages/eth_withdraw/README.md
> +<img align=“center” src="https://offchainlabs.com/c79291eee1a8e736eebd9a2c708dbe44.png" width="350" height="100">
Fixed :)

2021-05-04 14:57 UTC, mahsamoosavi commented on packages/eth_withdraw/contracts/Withdraw.sol
> +    function withdrawEth(address _destAddress) public payable
Sure, will do that.

2021-05-04 14:58 UTC, mahsamoosavi commented on packages/eth_withdraw/contracts/Arbsys.sol
> +interface ArbSys {
Agreed and Done.

2021-05-04 14:58 UTC, mahsamoosavi commented on packages/eth_deposit/scripts/deploy.js
> +    const l1Provider = new ethers.providers.JsonRpcProvider(`https://kovan.infura.io/v3/${infuraKey}`)
Sure, done.

2021-05-04 14:59 UTC, mahsamoosavi commented on packages/eth_deposit/package.json
> +    "build": "hardhat compile"
Added the ```"deploy": "hardhat run scripts/deploy.js"```.

I think we'd better keep everything in one single script (makes it easier for some users), will come up with a better name for it.

2021-05-04 14:59 UTC, mahsamoosavi commented on packages/eth_deposit/contracts/Payment.sol
> +    function depositEther(address _destAddress) public payable
Yeah right, I'll take some time explaining these too.

2021-05-07 10:01 UTC, fredlacs commented on packages/eth_withdraw/scripts/deploy.js
> +    const infuraKey = process.env.INFURA_KEY
I think thats a good move, then its straight forward for others to configure it for their own setup

2021-05-12 11:41 UTC, fredlacs requested changes

2021-05-12 11:41 UTC, fredlacs commented on packages/eth_deposit/.sample-env
> +RPCHOST = https://kovan4.arbitrum.io/rpc
We could call these `L1RPC` and `L2RPC` instead of rpchost and kovanhost to be clearer as to what they refer to

2021-05-12 11:41 UTC, fredlacs commented on packages/eth_deposit/scripts/exec.js
>  const inboxAddr = "0xD71d47AD1b63981E9dB8e4A78C0b30170da8a601";
We should probably add the inbox address to the .env as these can change through different releases (ie testnet v mainnet inboxes)
Same for the other packages

2021-05-12 11:41 UTC, fredlacs commented on packages/eth_deposit/README.md
hm the span style color doesn't seem to render in github. this might help https://github.github.com/gfm/#example-145

Also, I don't believe we should hardcode the kovan inbox address here as it will be a pain to maintain and might lead to confusion in the future if we change it and don't update this repo

2021-05-12 11:41 UTC, fredlacs commented on packages/eth_deposit/package.json
> +    "deploy": "hardhat run scripts/exec.js"
should we rename from `"deploy": "hardhat run scripts/exec.js"` to `"exec": "hardhat run scripts/exec.js"` for consistency?

2021-05-12 11:41 UTC, fredlacs commented on packages/eth_deposit/README.md
Another sidenote, I think its a good idea for us to keep the terminology neutral here. We don't need to specify the kovan testnet, but instead the Layer 1 where the interop example is running (which could be locally, rinkeby, kovan, etc)

2021-05-12 11:41 UTC, fredlacs commented on packages/eth_deposit/README.md
I think we could also add a "disclaimer" to make it very clear to users that you can just call the depositEth inbox function from your account instead of going through a contract. 
I'm not too sure about this, we could discuss it but I think the more clear we make it for users, the better.

2021-05-12 11:41 UTC, fredlacs commented on packages/eth_deposit/README.md
> +Once the script is successfully executed, you can go to the [Arbitrum block explorer](https://explorer.arbitrum.io), enter your public key, and see the amount of ETH that has been assigned to your ad
technically they need to enter their address, not the public key

2021-05-12 11:45 UTC, fredlacs commented
Ah also seems like the greeter package is not using the dependencies from `arb-shared-dependencies`

https://github.com/OffchainLabs/arbitrum-interop-quickstart/blob/0034770c32028bf44cdac4f313fed3ae92c028a9/packages/greeter/contracts/arbitrum/Arbsys.sol

2021-05-12 13:54 UTC, mahsamoosavi commented
> Ah also seems like the greeter package is not using the dependencies from `arb-shared-dependencies`
> 
> https://github.com/OffchainLabs/arbitrum-interop-quickstart/blob/0034770c32028bf44cdac4f313fed3ae92c028a9/packages/greeter/contracts/arbitrum/Arbsys.sol

yeah added Inbox, Outbox, and ArbSys to the dependency folder

2021-05-12 14:18 UTC, mahsamoosavi commented on packages/eth_deposit/README.md
added a line, let me know if that makes it clear

2021-05-13 12:05 UTC, fredlacs commented on packages/eth_deposit/README.md
You can also call through a contract if you send it funds :)

2021-05-13 12:05 UTC, fredlacs commented on packages/eth_deposit/README.md
by "just" I meant a simpler way haha my bad

2021-07-07 21:50 UTC, DZGoldman approved these changes

2021-07-07 21:50 UTC, merged